version: "3.1"

services:
  front:
    container_name: "Front_App"
    build: ./playstimation-front
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./playstimation-front:/usr/app/frontend
  back:
    container_name: "Back_API"
    build: ./backend
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./backend/:/usr/app/backend
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    
